name: Render Markdown to PDF using Quarto

on:
  push:
    branches:
      - publish
    paths:
      - README.md  # Only trigger the workflow when README.md changes
  workflow_dispatch:  # Allow manual trigger

jobs:
  render-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: quarto install tinytex --no-prompt

      - name: Remove first line from README.md
        run: tail -n +2 README.md > README_nofirst.md  # Ignore the first 2 lines in README.md (Zenodo badge)

      - name: Render README_nofirst.md to PDF
        run: quarto render README_nofirst.md --to pdf --output README.pdf

      - name: Move PDF to .publish folder
        run: |
          mv README.pdf .publish/README.pdf

      - name: Commit PDF
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .publish/README.pdf
          git commit -m "Add rendered README.pdf"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}